---
parse_config:
  zmk_additional_includes: ["zmk-helpers/include"]
draw_config:
  separate_combo_diagrams: true
  combo_diagrams_scale: 3
  svg_extra_style: "rect.held, rect.combo.held { fill: #222; }"
